"use client";

import { useEffect, useState } from "react";
import { getScenario } from "@/data/scenarios";
import {
  ENDING_META,
  SCORE_LABELS,
  StoredResult,
  averageScore,
} from "@/lib/game-engine";
import { Debrief, generateDebrief } from "@/lib/ai-review";
import ScorePanel from "@/components/ScorePanel";

interface ResultReportProps {
  result: StoredResult;
}

const toneStyles: Record<string, { ring: string; text: string; chip: string }> = {
  green: {
    ring: "ring-rescue-green/40",
    text: "text-rescue-green",
    chip: "bg-rescue-green/15 text-rescue-green",
  },
  amber: {
    ring: "ring-rescue-amber/40",
    text: "text-rescue-amber",
    chip: "bg-rescue-amber/15 text-rescue-amber",
  },
  red: {
    ring: "ring-rescue-red/40",
    text: "text-rescue-red",
    chip: "bg-rescue-red/15 text-rescue-red",
  },
};

/**
 * The post-call debrief: ending banner, score breakdown, and the AI-style
 * review (fetched from the mockable provider on mount).
 */
export default function ResultReport({ result }: ResultReportProps) {
  const scenario = getScenario(result.scenarioId);
  const ending = ENDING_META[result.ending];
  const tone = toneStyles[ending.tone] ?? toneStyles.amber;
  const avg = averageScore(result.scores);

  const [debrief, setDebrief] = useState<Debrief | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let active = true;
    setLoading(true);
    generateDebrief({
      scenarioId: result.scenarioId,
      scores: result.scores,
      ending: result.ending,
      decisions: result.decisions,
    }).then((d) => {
      if (active) {
        setDebrief(d);
        setLoading(false);
      }
    });
    return () => {
      active = false;
    };
  }, [result]);

  return (
    <div className="flex flex-col gap-6">
      {/* Ending banner */}
      <section
        className={`rounded-3xl border border-white/10 bg-night-soft/80 p-6 text-center ring-1 ${tone.ring}`}
      >
        {scenario && (
          <p className="mb-2 text-sm text-slate-400">
            {scenario.icon} {scenario.title} · {scenario.titleZh}
          </p>
        )}
        <div
          className={`mx-auto inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-semibold uppercase tracking-wide ${tone.chip}`}
        >
          {ending.label} · {ending.labelZh}
        </div>
        <p className="mt-4 text-lg font-medium text-slate-100">
          {ending.headline}
        </p>
        <p className={`mt-2 text-4xl font-bold tabular-nums ${tone.text}`}>
          {avg}
          <span className="text-base font-normal text-slate-400">/100</span>
        </p>
      </section>

      {/* Score breakdown */}
      <section>
        <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-400">
          Performance breakdown
        </h2>
        <ScorePanel scores={result.scores} variant="full" />
      </section>

      {/* AI debrief */}
      <section className="rounded-3xl border border-white/10 bg-night-soft/80 p-6">
        <div className="mb-4 flex items-center gap-2">
          <span className="flex h-8 w-8 items-center justify-center rounded-full bg-rescue-blue/20 text-rescue-blue">
            🤖
          </span>
          <div>
            <h2 className="text-sm font-semibold text-slate-100">
              AI Dispatcher Debrief
            </h2>
            <p className="text-[11px] text-slate-400">
              {loading
                ? "Reviewing your call…"
                : debrief?.source === "mock"
                  ? "Generated locally (demo mode)"
                  : "Generated by AI"}
            </p>
          </div>
        </div>

        {loading || !debrief ? (
          <div className="space-y-3" aria-hidden>
            <div className="h-4 w-3/4 animate-pulse rounded bg-white/10" />
            <div className="h-4 w-full animate-pulse rounded bg-white/10" />
            <div className="h-4 w-5/6 animate-pulse rounded bg-white/10" />
          </div>
        ) : (
          <div className="space-y-5 text-sm leading-relaxed">
            <p className="text-slate-200">{debrief.summary}</p>

            <div>
              <h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-rescue-green">
                What you did well
              </h3>
              <ul className="space-y-1.5">
                {debrief.strengths.map((s, i) => (
                  <li key={i} className="flex gap-2 text-slate-300">
                    <span className="text-rescue-green">✓</span>
                    <span>{s}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div>
              <h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-rescue-amber">
                For next time
              </h3>
              <ul className="space-y-1.5">
                {debrief.improvements.map((s, i) => (
                  <li key={i} className="flex gap-2 text-slate-300">
                    <span className="text-rescue-amber">→</span>
                    <span>{s}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="rounded-2xl bg-rescue-blue/10 p-4">
              <h3 className="mb-1 text-xs font-semibold uppercase tracking-wide text-rescue-blue">
                Key takeaway
              </h3>
              <p className="text-slate-200">{debrief.keyTakeaway}</p>
            </div>

            <p className="border-t border-white/10 pt-4 text-xs italic text-slate-400">
              {debrief.disclaimer}
            </p>
          </div>
        )}
      </section>
    </div>
  );
}
